### ISSUE TITLE
Writing tree to nexus file

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.archive#3]
When I use `save=trees.tre`, the TRANSLATE table include spaces between genus and species in taxon names, surrounding space-bearing taxa in 'single quotes'.

I can only open this file using `ape::read.nexus` if I replace these spaces with underscores.

I'm not sure whether this is an issue with Morphy or with R's ape package... should Morphy be writing underscores, or does the NEXUS specification allow for spaces (in which case I'll post an issue with 'ape'!)

**Comment by mbrazeau** [comment]
That appears to be a limitation of ape. Morphy does extremely little in terms of writing/reading file data itself. Nearly all of that is handled by the Nexus Class Library which is about as standard-conforming as anything gets.
