### ISSUE TITLE
Counting parsimony-uninformative characters

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.archive#5]
Using morphy_nui_v0b1Winx64.exe and [hyo.nex](https://github.com/mbrazeau/morphy.release.test/files/4117015/hyo.nex.txt)

```
open = hyo.nex
heuristic
```
reports `-1 characters are parsimony uninformative`.

**Comment by mbrazeau** [comment]
I've fixed this for 0.3b.
