### ISSUE TITLE
Ratchet output: "shortest tree" vs. "best tree"

### ISSUE THREAD

**Issue by ms609** [mbrazeau/morphy.archive#6]
In the output below, I'm a bit confused by the difference between "Best tree" and "Shortest tree".  Could "Best tree" be replaced with a fuller description, e.g. "Best tree this replicate"? 

I suspect that the text displayed pertains to the 50th ratchet iteration? If so, is it possible to update the text after the final iteration with a summary, i.e. "Shortest Tree Found" and "Number of Trees Saved" values matching the summary statistics for the entire replicate?

```
Running: heuristic
Dataset has 225 characters
         -1 characters are parsimony uninformative
         59 characters are treated as type "inapplicable"
Replicate: 1
Initiating ratchet search
        Ratchet iteration 50. Best tree: 628 steps
        Replicate completed.
        Shortest tree found: 628 steps
        Number of trees saved: 0

Replicate: 2
Initiating ratchet search
        Ratchet iteration 50. Best tree: 628 steps
        Replicate completed.
        Shortest tree found: 629 steps
        Number of trees saved: 0

Replicate: 3
Initiating ratchet search
        Ratchet iteration 50. Best tree: 628 steps
        Replicate completed.
        Shortest tree found: 634 steps
        Number of trees saved: 0

Heuristic search completed in 115 seconds:
        16584446 rearrangements tried.
        Shortest tree found: 628.000 steps
        7 trees saved
```

**Comment by mbrazeau** [comment]
This all needs tidying up. Best tree is best overall. The "shortest tree" message is just the length of the last tree checked with normal weights. That's why the output looks confusing. This whole output format will be changed, but I'll leave the issue open because other users are likely to encounter this.
